### ISSUE TITLE
returnOpenOrders not returning my open orders

### ISSUE THREAD

**Issue by junw3i** [sammchardy/python-idex#1]
I couldn't spot any error on your `returnOpenOrders` call but it's returning ```"error": "Cannot read property 'toLowerCase' of undefined"``` 

So I just started playing around with idex's API today so I'm not sure if this is an issue on idex's API or there is a real issue with your wrapper.

**Comment by junw3i** [comment]
I'm pretty sure its an issue on their endpoint after reviewing your code again.

**Comment by sammchardy** [comment]
Hi @junw3i that does look like a JavaScript error so most likely the server having issues. If you're still experiencing the issue you could try raising it on the Telegram channel https://t.me/Auroradaochat

**Comment by jnorthrup** [comment]
{"error":"Cannot read property 'toLowerCase' of undefined"}
ditto here....  works sometimes, stops working sometimes...
