### ISSUE TITLE
unable to initiate client

### ISSUE THREAD

**Issue by ds0506** [sammchardy/python-idex#10]
I setup and run the code as specified in the docs. However, this error message shows up.

Traceback (most recent call last):
  File "idexV2.py", line 1, in <module>
    from idex.client import Client
  File "/usr/local/lib/python3.5/dist-packages/idex/client.py", line 10, in <module>
    from ethereum.utils import sha3, ecsign, encode_int32
  File "/usr/local/lib/python3.5/dist-packages/ethereum/__init__.py", line 11, in <module>
    from . import slogging  # noqa
  File "/usr/local/lib/python3.5/dist-packages/ethereum/slogging.py", line 6, in <module>
    from ethereum.utils import bcolors, is_numeric
  File "/usr/local/lib/python3.5/dist-packages/ethereum/utils.py", line 13, in <module>
    from rlp.utils import decode_hex, encode_hex, ascii_chr, str_to_bytes
ImportError: cannot import name 'decode_hex'

**Comment by khranovsky1337** [comment]
Oh, I had this issue too
There is a problem in ethereum repository -  they've updated the rlp module and ethereum modules, but didn't pushed update in ethereum PyPI, so solution is clone repo from https://github.com/ethereum/pyethereum and run in this directory "python setup.py install"
Now, go to the site-packages in python directory and move ethereum directory from ethereum-2.3.1 and so on to site-packages/ethereum with replace

**Comment by shashank-ezdiagno** [comment]
just make a new pull request, looks like the decode_hex function is now in eth_utils

**Comment by dipeshsoni005** [comment]
great khranovsky1337's worked

**Comment by sammchardy** [comment]
Hi @ds0506 can you try updating to v0.3.0 and see if it helps

**Comment by mmoravcik** [comment]
@sammchardy with 0.3.0 getting 

```
from rlp.utils import str_to_bytes
ImportError: cannot import name 'str_to_bytes'
```

**Comment by sammchardy** [comment]
@mmoravcik which version of Python are you running? are you on Mac, Linux or Windows?

**Comment by mmoravcik** [comment]
Python 3.6.5 @ mac

Have you tried the clean install of 0.3.0? I am getting missing libraries like `rlp`, `Crypto` and `requests`

**Comment by sammchardy** [comment]
@mmoravcik oh you're right. Sorry the setup.py requirements function wasn't actually returning anything that would do it.

Have pushed v0.3.1

**Comment by mmoravcik** [comment]
@sammchardy unfortunately, still getting

```
  File "/Users/fantiago/.virtualenvs/cryptotrage/lib/python3.6/site-packages/idex/utils.py", line 10, in <module>
    from rlp.utils import str_to_bytes
ImportError: cannot import name 'str_to_bytes'
```

**Comment by sammchardy** [comment]
@mmoravcik ok give v0.3.2 a spin.
