### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by khranovsky1337** [sammchardy/python-idex#11]
Hey, when I'm trying to install your library on Windows, it crashes with error code 1. I googled the error reason and it was a incompatibility in pyethash library. Hm, is it possible to delete it from dependencies, maybe try to replace sha-3 hash implementation from another sources?

UPD: I found the possible solution, but it isn't convenient.
So, the problem is in the ethash lib. First, clone its repo from https://github.com/ethereum/ethash
Now, follow the instrcutions I found:

Installing ethash on Windows:

Open \src\libethash\mmap_win32.c for editing
Add the following after the last #include statement
#pragma comment(lib, "Shell32.lib")

Open \src\python\core.c
Replace:
#include <alloca.h>
with:
#if defined(_WIN32) || defined(WIN32)
#include <malloc.h>
#else
#include <alloca.h>
#endif

Run the following in the source code main folder

setup.py install

Now, when ethash is installed, you are able to install python-idex,  run:
pip install python-idex. As ethash is already installed, it won't try to install it and all be OK.

**Comment by sammchardy** [comment]
Hi @khranovsky1337 can you try updating to v0.3.0 and see if it helps

**Comment by khranovsky1337** [comment]
Looks like this helped, yes, thx
