### ISSUE TITLE
Can't get next nonce

### ISSUE THREAD

**Issue by Dzhei52** [sammchardy/python-idex#14]
Hello!
When I try to init client like 
self.__client = Client(address, pk)
I got an error from idex:
{'result': 'error', 'errors': ['[LAMBDA-RUNNER]\n    FAILED TO INITIALIZE LAMBDA! \n    \n    Our initialization function expects either one or two arguments, however, \n    you provided 3 parameters.', "Cannot set property 'agent' of undefined"]}

It is a result of get_next_nonce(address) function.
What could be wrong?
Thanks!

**Comment by gwbischof** [comment]
I am having a similar problem with getting the next nonce, this is my output:

~/anaconda3/envs/pyth36/lib/python3.6/site-packages/idex/client.py in set_wallet_address(self, address, private_key)
    168         self._wallet_address = address.lower()
    169         nonce_res = self.get_my_next_nonce()
--> 170         self._start_nonce = nonce_res['nonce']
    171         if private_key:
    172             if re.match(r"^0x[0-9a-zA-Z]{64}$", private_key) is None:

KeyError: 'nonce'

**Comment by abrahamchaibi** [comment]
Same here. `{ result: 'error',
  errors:
   [ '[LAMBDA-RUNNER]\n    FAILED TO INITIALIZE LAMBDA! \n    \n    Our initialization function expects either one or two arguments, however, \n    you provided 3 parameters.',
     'Cannot set property \'agent\' of undefined' ] }`

**Comment by sammchardy** [comment]
This was a server issue
