### ISSUE TITLE
Facing ImportError while trying to use get_currencies() without private key initialisation

### ISSUE THREAD

**Issue by nandubatchu** [sammchardy/python-idex#17]
Using version 0.3.2:

Traceback:
ImportError: dlopen(/Users/{venv}/lib/python3.6/site-packages/coincurve/_libsecp256k1.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /Users/{venv}/lib/python3.6/site-packages/coincurve/_libsecp256k1.cpython-36m-darwin.so
  Reason: image not found

**Comment by blaaaaaaa** [comment]
on macos python 3.6.4 got the same error, with or without key. 
`brew install gmp`
solved the matter for me, but don't know why.
