### ISSUE TITLE
v, r, and s are not being sent in order

### ISSUE THREAD

**Issue by Lvl4Sword** [sammchardy/python-idex#19]
https://github.com/AuroraDAO/idex-api-docs#order shows more variables that client.create_order is not sending.

> All signatures must be in the { v, r, s } form where v is a Number type between 27 and 28, and r and s are both hex strings with the standard 0x prefix.

https://github.com/sammchardy/python-idex/blob/master/idex/client.py#L1307 does not send this information.

Please fix?

**Comment by sammchardy** [comment]
Hi @Lvl4Sword are you having an issue with this function?

The v, r and s variables are generated for all signed requests, so this is done centrally in the `_generate_signature` function in client.py.

**Comment by Lvl4Sword** [comment]
Was something I spent very little time on admittedly. I'll look into it further, thank you!
