### ISSUE TITLE
Deposit / Withdrawal

### ISSUE THREAD

**Issue by Oshawk** [sammchardy/python-idex#2]
Hello,

Is there any time-frame on when deposit / withdrawal will be implemented? I really like your API wrappers and hope to use them on a couple of projects but this functionality is essential for that.

Thanks,
Joseph.

**Comment by Oshawk** [comment]
Just realized I could probably just withdraw from the associated wallet.

**Comment by sammchardy** [comment]
Hi @Oshawk, yes with IDEX you are always in control of your wallet.

I do plan on implementing them when I have some time. Withdrawing should be easier than Depositing to include as it is just an API call. Whereas Depositing requires a contract call on the ETH network and probably needs some other libraries to implement it.

**Comment by Oshawk** [comment]
@sammchardy Okay, great, it is only really a convince thing. By the way, you don't happen to know of any other ERC-20 exchanges where you control your own wallet that have easyish to use APIs (already know of EtherDelta and Radar Relay but both have really complicated APIs).

**Comment by sammchardy** [comment]
Hi @Oshawk in v0.2.1 I've added in the withdraw functionality.

Depositing is going to take a little more time.

I'm not aware of any other exchanges like that, if you find one let me know.

**Comment by Oshawk** [comment]
@sammchardy Okay, great!

I know I am pushing my luck now but if you made an easy to use API wrapper for EtherDelta I think quite a few people would be greatfull (me especially :stuck_out_tongue:).

Thanks again,
Joseph.

**Comment by sammchardy** [comment]
@Oshawk come say Hi on Telegram and let me know what's lacking in the current EtherDelta wrappers. https://t.me/sammchardy
