### ISSUE TITLE
Upcoming updates

### ISSUE THREAD

**Issue by bradennapier** [sammchardy/python-idex#34]
Hey!  Awesome library!  I work with IDEX and just wanted to get in touch if possible about the upcoming changes to our realtime API and work with you to make sure this library is ready for the change! 

I am "+B" in our Discord if you wanted to get in touch, there is a "#developers" chat there, we also released the first draft of the Typescript library offering it: https://github.com/AuroraDAO/datastream-client-js

Let me know!  Thanks!

**Comment by sammchardy** [comment]
Thanks @bradennapier I have pushed v0.3.5 which handles the new datastream endpoint with exponential backoff.
Subscribe and unsubscribe are flexible and may need some more docs around how people use unsubscribe.
Similarly with account and chain message categories.

**Comment by bradennapier** [comment]
Awesome!  Closing, thanks!
