### ISSUE TITLE
get all open orders from an address (get_open_orders)

### ISSUE THREAD

**Issue by ppoursaf** [sammchardy/python-idex#38]
Hello,
It will be cool if we can have all open orders in all markets from one address.
I saw that we can do that in Idex API if you put an empty string for the market variable.

Thanks a lot for your lib, you are genius :)

**Comment by ppoursaf** [comment]
up ?

**Comment by ppoursaf** [comment]
pd

**Comment by sammchardy** [comment]
Hi @ppoursaf I don't believe this is possible. From the API docs here https://docs.idex.market/#operation/returnOpenOrders it says `Returns a paginated list of all open orders for a given market or address.`
