### ISSUE TITLE
Cancel signature invalid

### ISSUE THREAD

**Issue by rfenzo** [sammchardy/python-idex#6]
I've been able to make new orders, but when I try to cancel them, i'm getting this signature error. Any ideas?

`Traceback (most recent call last):
  File "/home/rfenzo/CryptoWallet/code/idextrader.py", line 33, in <module>
    client.cancel_order(last_buy_order)
  File "/home/rfenzo/.local/lib/python3.5/site-packages/idex/client.py", line 1397, in cancel_order
    return self._post('cancel', True, hash_data=hash_data, json=json_data)
  File "/home/rfenzo/.local/lib/python3.5/site-packages/idex/client.py", line 144, in _post
    return self._request('post', path, signed, **kwargs)
  File "/home/rfenzo/.local/lib/python3.5/site-packages/idex/client.py", line 123, in _request
    return self._handle_response(response)
  File "/home/rfenzo/.local/lib/python3.5/site-packages/idex/client.py", line 135, in _handle_response
    raise IdexAPIException(response)
idex.exceptions.IdexAPIException: IdexAPIException: Cancel signature invalid. Please try again.`

where the order is placed like this:
```
order = client.create_order(...)
last_buy_order = order["orderHash"]
```

**Comment by sammchardy** [comment]
Hi @rfenzo do you have the latest version v0.2.3?

There were some recent fixes for the cancel order signature generation.

**Comment by rfenzo** [comment]
Yes, I also reinstalled the package. 

`sudo pip3 install python-idex
[sudo] password for rfenzo: 
The directory '/home/rfenzo/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/rfenzo/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting python-idex
  Downloading python_idex-0.2.3-py2.py3-none-any.whl
Requirement already satisfied: ethereum in ./.local/lib/python3.5/site-packages (from python-idex)
Requirement already satisfied: requests in ./.local/lib/python3.5/site-packages (from python-idex)
Requirement already satisfied: pysha3>=1.0.1 in ./.local/lib/python3.5/site-packages (from ethereum->python-idex)
Requirement already satisfied: future in ./.local/lib/python3.5/site-packages (from ethereum->python-idex)
Requirement already satisfied: py-ecc in ./.local/lib/python3.5/site-packages (from ethereum->python-idex)
Requirement already satisfied: rlp>=0.4.7 in ./.local/lib/python3.5/site-packages (from ethereum->python-idex)
Requirement already satisfied: PyYAML in ./.local/lib/python3.5/site-packages (from ethereum->python-idex)
Requirement already satisfied: pyethash in ./.local/lib/python3.5/site-packages (from ethereum->python-idex)
Requirement already satisfied: scrypt in ./.local/lib/python3.5/site-packages (from ethereum->python-idex)
Requirement already satisfied: repoze.lru in ./.local/lib/python3.5/site-packages (from ethereum->python-idex)
Requirement already satisfied: pbkdf2 in ./.local/lib/python3.5/site-packages (from ethereum->python-idex)
Requirement already satisfied: pycryptodome>=3.4.7 in ./.local/lib/python3.5/site-packages (from ethereum->python-idex)
Requirement already satisfied: idna<2.7,>=2.5 in ./.local/lib/python3.5/site-packages (from requests->python-idex)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./.local/lib/python3.5/site-packages (from requests->python-idex)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.5/site-packages (from requests->python-idex)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/lib/python3.5/site-packages (from requests->python-idex)
Installing collected packages: python-idex
Successfully installed python-idex-0.2.3`

**Comment by rfenzo** [comment]
I've tried several times checking the code and the api documentation searching an error, but my inexperienced eyes can't find the error. May I get a little help here please?

**Comment by blaaaaaaa** [comment]
Hi, having the same issue with 0.2.3 and 0.2.4, any help?

**Comment by sammchardy** [comment]
Hi @rfenzo and @blaaaaaaa I really thought I'd included this in the last releases, sorry about that.

v0.2.5 now works as expected.

**Comment by rfenzo** [comment]
Thank you @sammchardy !. Now I got another problem,you broke the get_my_balances function as I can see. The get_balances() receives a token name or contract address, and a boolean, and get_my_balances() calls get_balances(self._wallet_address,boolean), so it raises and error when trying to find a token with a contract address like your wallet_address.

`Traceback (most recent call last):
  File "/home/rfenzo/Desktop/untitled.py", line 7, in <module>
    print(client.get_my_balances())
  File "/usr/local/lib/python3.5/dist-packages/idex/client.py", line 885, in get_my_balances
    return self.get_balances(self._wallet_address, complete)
  File "/usr/local/lib/python3.5/dist-packages/idex/client.py", line 832, in get_balances
    currency = self.get_currency(token)
  File "/usr/local/lib/python3.5/dist-packages/idex/client.py", line 780, in get_currency
    raise IdexCurrencyNotFoundException(currency)`

**Comment by rfenzo** [comment]
get_balances(token) is also failing, it only works for 'ETH' as far i can see.

**Comment by rfenzo** [comment]
placing an order is also failing now, it puts an order with an extremely high price (in my case was 86 eth for each token I was trading), i don't know why

**Comment by sammchardy** [comment]
ok v0.2.7 will resolve that
