### ISSUE TITLE
get_order_book() does not work

### ISSUE THREAD

**Issue by Juraganet** [sammchardy/python-idex#9]
I always get this error when trying get_order_book(ETH_ICX)
idex.exceptions.IdexAPIException: IdexAPIException: Market ETH_ICX not found

**not only ICX, I tried every possible token, all returning same error.
**edit

I found they use another URL and path to get orderbook, here's my simple python script to get orderbook:

url = 'https://ns5qa7zsuj.execute-api.ca-central-1.amazonaws.com/prod/returnOrderBookForMarket'
payload = {"selectedMarket":"ETH","tradeForMarket":"AION"}
r = requests.post(url, data=json.dumps(payload))
js = json.loads(r.content.decode('utf-8'))

**Comment by joshuaeitan** [comment]
How did you find that URL? That seems to be what the idex docs call the 'returnOpenOrders' endpoint, do you know the URL for the 'returnOrderBook' endpoint (as described in the idex docs)?

**Comment by Juraganet** [comment]
Yes I know its /returnOrderBook?market=AION_ETH

I found out the function works fine, the problem was IDEX server not active (in maintenance mode) during the moment.

Thanks!

**Comment by joshuaeitan** [comment]
Oh, maybe thats the issue I was having too. thanks for your help!

**Comment by Juraganet** [comment]
The Amazon URL above was found by sniffing from Cloudflare.

**Comment by Juraganet** [comment]
May I ask you a question? I know how to BUY using this API, but how to SELL? I tried once but my order did not matched with the existing top orderbook even I have matched the volume of 'ETH' (amount of buy_token)

**Comment by khranovsky1337** [comment]
This code doesn't work now, sad, result is internal server error

**Comment by Juraganet** [comment]
code is fine, the problem is IDEX server does not response rightly

**Comment by sammchardy** [comment]
Closing because of server issue
